---
- name: Vector | Download rpm-distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
    mode: 0644

# - name: Vector | Patch Centos8
#   when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"
#   become: true
#   ansible.builtin.command: "{{ item }}"
#   args:
#     chdir: "/etc/yum.repos.d/"
#   with_items:
#     - "sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*"
#     - "sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"

- name: Vector | Install rpm-packages
  become: true
  ansible.builtin.yum:
    name: "vector-{{ vector_version }}.rpm"
